name: Build on Push

on:
  push:
    branches:
      - main  # Change this to your branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install nasm and xorriso
      run: |
        sudo apt-get update
        sudo apt-get install -y nasm xorriso
      
    - name: Run build script
      run: |
        chmod +x build.sh
        ./build.sh

